<footer>
	<?php include('../includes/nav.inc');?>
	<cite>&copy; 2000 &ndash; 2013 The Site. All rights reserved.</cite>
</footer>
</div>
<script src="assets/libs/jquery/min/jquery.min.js"></script>
<script src="assets/js/min/core.min.js"></script>
<script src="assets/plugins/jquery/min/slimbox2.min.js"></script>
<script src="assets/plugins/jquery/min/jquery.cycle.all.min.js"></script>
</body>
</html>
