<base href="http://localhost/Work_Flow_Exercise/" />
<script src="assets/libs/modernizr/min/modernizr.min.js"></script>
<link href="assets/css/core.css" rel="stylesheet" />
<link href="assets/css/slimbox2.css" rel="stylesheet" />
<style>
	section{
		display: block;
	}
	#clients{
		margin: 2em 0;
		height: 20em;
	}
	#portfolio img{
		width: 100%;
	}
	#clients img{
		width: 10em;
	}
	#lbImage{
		width: 640px;
		height: 480px;
		background-size: contain;
	}
</style>
</head>
<body>
<div id="wrapper">
<header>
	<h1>The site</h1>
        <?php include('../includes/nav.inc');?>
</header>